### Corizo

In [2]:
def print_lyrics():
    print("hello")
    print("fine")

def repeat_lyrics():
    print_lyrics()
    print_lyrics()

repeat_lyrics()

hello
fine
hello
fine

In [2]:
def add(a, b):
    print(a + b)

add(2, 7)
print("hi")

9
hi

In [ ]:
def fact(x):
    if x==0 or x==1:
        return 1
    else:
        return x * fact(x-1)
    
en=int(input("Enter the number:"))
if en <= 0:
    print(f"{en}: this number is not allowed,typer some other number")
else:
    print(f"The factorial of {en} is:{fact(en)}")    
    
# print(fact(4))

In [20]:
def f(n):
    result=1
    for i in range(1,n+1):
        result*=i
        print(result)
    return result

f(4)

1
2
6
24

24

In [21]:
a=2
b=1
a=b
a

1

In [22]:
def recurse(n,s):
    if n==0:
        print(s)
    else:
        recurse((n-1),n+s)
recurse(3,0)

6

In [23]:
for i in range(1,20,2):
    print(i)

1
3
5
7
9
11
13
15
17
19

In [25]:
for i in range(1,10):
    print(i,end="-")

1-2-3-4-5-6-7-8-9-

In [2]:
for i in range(-1,-10-1,-1):
    print(i)

-1
-2
-3
-4
-5
-6
-7
-8
-9
-10

In [34]:
def count(n):
    while n>0:
        print(n)
        n-=1
    print("blast off")    
count(5)

5
4
3
2
1
blast off

In [36]:
while True:
    line=input(">")
    if line=="Done":
        break
    print(line)

g
f
d
gg

In [38]:
n=1
while True:
    if n>=11:
        break
    print(n)
    n+=1

1
2
3
4
5
6
7
8
9
10

In [47]:
# Strings

fruit="Banana"
print(fruit)

print(fruit[2])

print(fruit[-3])

print(fruit[::-1])

Banana
n
a
ananaB

In [4]:
fruits="Pineapple"
for i in fruits:
    print(i,end="")
len(fruits)

Pineapple

9

In [52]:
fruits="Pineapple"
n=0
while n<len(fruits):
    print(fruits[n])
    n+=1

P
i
n
e
a
p
p
l
e

In [59]:
#Concat
first_name="Thirumalesh"
last_name="V"
full_name=first_name+last_name
print(full_name)

len(last_name*4)

ThirumaleshV

4

In [62]:
prefix="JSPD"
suffix="ack"
suffix2="aok"

for letters in prefix:
    if letters=="J" or letters=="P":
        print(letters+suffix)
    else:
        print(letters+suffix2)

Jack
Saok
Pack
Daok

In [64]:
s="Monty Python"
print(s[2:8])
print(s[-1:-5:-1])

nty Py
noht

In [65]:
h="Hello"
print("T"+h[1:])

Tello

In [ ]:
name="Thirumaleh"
if "h" in name:
    print("yes")
else:
    print("No")

yes

In [6]:
W="THIRUMALESH"
print(W.find('H',2))
print(W.find('o'))
print(W.find('RU'))

10
-1
3

In [77]:
name="Thiru"
new=name.upper()
print(new)

THIRU

In [78]:
#lists
cheese=["chader","milk"]
print(cheese)

['chader', 'milk']

In [81]:
num=[5,10]
for i in range(len(num)):
    num[i]*=2
print(num)

[10, 20]

In [18]:
num=[5,10]
for i in num:
    print(type(i))

<class 'int'>
<class 'int'>

In [85]:
t=[True,"Hello",3,["fruit","vegi"]]
t[3][1]

'vegi'

In [88]:
def palindrome(n):
    if n==n[::-1]:
        print(n,"is a 'palindrome'")
    else:
        print(f"{n}is not a palindrome")
take=input("Enter name to check:")
palindrome(take)

HelleH is a 'palindrome'

In [6]:
che=[1,2,3,4,5,6,7,8,9,10]
che[-2:-5:-1]

[9, 8, 7]

In [15]:
t=["a","b","c","d","e","f","A"]
t[1:3]=["x","y"]
t.extend(["t","r"])
t.sort()
t

['A', 'a', 'd', 'e', 'f', 'r', 't', 'x', 'y']

In [23]:
def tot(n):
    total=0
    for i in n:
        total+=i
    print(type(total))    
    return total    

tot([1,2,3,4])

<class 'int'>

10

In [25]:
def upper(s):
    lis=[]
    for i in s:
        if i.isupper():
            lis.append(i)
    return lis
upper(["e","A","q","B"])

['A', 'B']

In [28]:
h1="Tanvi"
h2="tanvi"
print(id(h1))
print(id(h2))

2210660856288
2210660988752

In [32]:
t1=[1,2,3,]
t2=t1+[4]
t2

[1, 2, 3, 4]

In [ ]:
# string to list
s="spam"
t=list(s)
t

['s', 'p', 'a', 'm']

In [51]:
s="i like to, play"
t=s.split()
type(t)
len(t)
t

['i', 'like', 'to,', 'play']

In [11]:
# list to string 
t=["a","b"]
s=" ".join(t)
type(s)
print(s)

a b

In [13]:
# Dictionaries
di={"one":1,"two":2,"three":3}
v=di.values()
v
di["one"]=11
di

{'one': 11, 'two': 2, 'three': 3}

In [76]:
def rep(n):
    d={}
    for i in n:
        if i not in d:
            d[i]=1
        else:
            d[i]+=1
    return d

rep("thirumalesh")           
rep("AABCCCC")

{'A': 2, 'B': 1, 'C': 4}

In [ ]:
t=123
h=str(t)

str

In [ ]:
# tuples
t=(1,2,3)
t[1]
new_t=(4,5)+t[:]
new_t

(4, 5, 1, 2, 3)

In [95]:
a=1
b=2
def switch(a,b):
    x=a
    a=b
    b=x
    print("a is:",a,"B is :",b)

switch(a,b)

t=1
v=2
t,v=v,t
print(v)

a is: 2 B is : 1
1

In [99]:
email="thiurmalesh4323@gmail.com"
username,domain=email.split("@")
print(username)
print(domain)

thiurmalesh4323
gmail.com

In [105]:
t=(1,2,3)
type(t)
max(t)
sum([1,2,3])

6

In [111]:
t=[("a",0),("b",1)]
for letter,number in t:
    p=letter,number
    print(p)
print(type(p))

('a', 0)
('b', 1)
<class 'tuple'>

In [19]:
# dict to tuples
dict={"a":1,"b":2,"c":3}
t=dict.items()
print(type(t))
ch1=list(dict.items())
ch2=tuple(dict.items())
print(type(ch1))
print(type(ch2))

for key ,value in t:
    print(key,value)

ch1[0]

<class 'dict_items'>
<class 'list'>
<class 'tuple'>
a 1
b 2
c 3

('a', 1)

In [20]:
del dict

In [21]:
# tuples to dict 
t=(("a",0),("b",2))
d=dict(t)
d
type(t)
d

{'a': 0, 'b': 2}

In [22]:
emp_id=[1,2,3,4,5]
emp_name=["A","B","C","D"]
emp_info=dict(zip(emp_id,emp_name))
print(emp_info)

{1: 'A', 2: 'B', 3: 'C', 4: 'D'}

In [ ]:
s="abc"
t=[0,1,2]
for pair in zip(s,t):
    print(pair)
print(type(pair))    
print()

p=zip(s,t)
for i in p:
    print(i)


list(zip(s,t))

q=tuple(zip("hello","python"))
p=list(zip("hello","python"))

d = dict(zip("abc", range(3)))

('a', 0)
('b', 1)
('c', 2)
<class 'tuple'>

('a', 0)
('b', 1)
('c', 2)

(('h', 'p'), ('e', 'y'), ('l', 't'), ('l', 'h'), ('o', 'o'))

In [156]:
ord("H")

72

In [5]:
l=[1,2,3,4,5]
for i in range(len(l)):
    l[i] += 1
print(l)

[2, 3, 4, 5, 6]

### Numpy

In [9]:
import numpy as np

data=np.random.randn(2,3)
print(data)

[[ 1.93403013 -0.64699528  0.85985235]
 [ 0.11830092  1.3759666  -0.92619609]]

In [3]:
data*10

array([[  1.91489695,   9.7543656 ,  14.77170059],
       [-19.01038688,  -3.73733015, -10.89709831]])

In [4]:
data.shape

(2, 3)

In [14]:
#list to numpy
data=[3,2,4,5,1]
arr1=np.array(data)
print(type(arr1))

<class 'numpy.ndarray'>

In [15]:
data=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.shape

(2, 4)

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [2]:
#arange
import numpy as np
i=np.arange(0,10,1)
i

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#convert float array to int array
arr=np.array([3.7,-1.1,-2.6])
print(arr)

[ 3.7 -1.1 -2.6]

In [4]:
arr.dtype

dtype('float64')

In [6]:
arr.astype(np.int64)

array([ 3, -1, -2])

In [8]:
import numpy as np

In [9]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]

In [10]:
arr1+arr1

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [12]:
10/arr1

array([[10.        ,  5.        ,  3.33333333],
       [ 2.5       ,  2.        ,  1.66666667]])

In [13]:
a1=np.array([1,8,3])
a2=np.array([4,5,6])
a1>a2

array([False,  True, False])

In [15]:
i=np.arange(5,10)
i

array([5, 6, 7, 8, 9])

In [16]:
i[2]

np.int64(7)

In [ ]:
i[2]=6 # mutable

In [18]:
print(i)

[5 6 6 8 9]

In [ ]:
#slicing
arr=np.arange(5,10)
arr[0:4]

array([5, 6, 7, 8])

In [11]:
arr[::2]

array([5, 7, 9])

In [ ]:
arr[0:2]

array([5, 6])

In [13]:
arr[0:2]=-1

In [14]:
arr[0:2]

array([-1, -1])

In [15]:
print(arr)

[-1 -1  7  8  9]

In [ ]:
#
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [22]:
arr[1,2]

np.int64(6)

In [23]:
arr[:,1]

array([2, 5, 8])

In [29]:
arr[2,0]=1

In [30]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 8, 9]])

## Pandas

In [1]:
import pandas as pd

In [5]:
Data=pd.Series([1,2,3,-4])
print(Data)

0    1
1    2
2    3
3   -4
dtype: int64

In [6]:
Data.values

array([ 1,  2,  3, -4])

In [7]:
Data.index

RangeIndex(start=0, stop=4, step=1)

In [40]:
Data1=pd.Series([11,15,22,-3],index=[1,2,3,4])
Data1

1    11
2    15
3    22
4    -3
dtype: int64

In [41]:
Data1=pd.Series({11:1,15:2,22:3,-3:4})
Data1

 11    1
 15    2
 22    3
-3     4
dtype: int64

In [39]:
Data1=pd.Series({11:1,15:2,22:3,-3:4},index=[11,15,22,-3])
Data1

 11    1
 15    2
 22    3
-3     4
dtype: int64

In [13]:
Data1.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [14]:
Data1[["a","b"]]

a    11
b    15
dtype: int64

In [16]:
"c" in Data1

True

In [17]:
"f" in Data1

False

In [34]:
Data1=pd.Series([11,15,22,-3],index=range(1,5))
Data1

1    11
2    15
3    22
4    -3
dtype: int64

In [25]:
pd.Series(sdata)

ohio       123
Texas      456
Oregon     789
utah      1478
dtype: int64

In [29]:
sdata={"ohio":123,"Texas":456,"Oregon":789,"utah":1478}
o=pd.Series(sdata,index=["califorina",'ohio','Oregon','Texas'])
o

califorina      NaN
ohio          123.0
Oregon        789.0
Texas         456.0
dtype: float64

In [42]:
sdata={"ohio":123,"Texas":456,"Oregon":789,"utah":1478}
o=pd.Series(sdata,index=["ohio"])
o

ohio    123
dtype: int64

In [43]:
sdata={"ohio":123,"Texas":456,"Oregon":789,"utah":1478}
sdata

{'ohio': 123, 'Texas': 456, 'Oregon': 789, 'utah': 1478}

In [44]:
states=["califorina",'ohio','Oregon','Texas']
obj4=pd.Series(sdata,index=states)
obj4

califorina      NaN
ohio          123.0
Oregon        789.0
Texas         456.0
dtype: float64

In [45]:
pd.isna(obj4)

califorina     True
ohio          False
Oregon        False
Texas         False
dtype: bool

In [46]:
pd.notnull(obj4)

califorina    False
ohio           True
Oregon         True
Texas          True
dtype: bool

In [47]:
pd.isnull(obj4)

califorina     True
ohio          False
Oregon        False
Texas         False
dtype: bool

In [3]:
#data frame

data={"states":['ka','tn','ap'],
      'year':[2005,2006,2007],
      'pop':[1.5,1.6,1.7]}
print(data)

{'states': ['ka', 'tn', 'ap'], 'year': [2005, 2006, 2007], 'pop': [1.5, 1.6, 1.7]}

In [4]:
h=pd.DataFrame(data)
h

  states  year  pop
0     ka  2005  1.5
1     tn  2006  1.6
2     ap  2007  1.7

In [5]:
h.iloc[1,1]

np.int64(2006)

In [6]:
h.loc[1,'year']

np.int64(2006)

In [7]:
h.iloc[:,:2]

  states  year
0     ka  2005
1     tn  2006
2     ap  2007

In [8]:
h.loc[:,["states","year"]]

  states  year
0     ka  2005
1     tn  2006
2     ap  2007

In [11]:
h.iloc[0:1,:]

  states  year  pop
0     ka  2005  1.5

In [14]:
#data cleaning
import pandas as pd
import numpy as np
from numpy import nan as NA
string_data=pd.Series(["ardvark","artichoke",NA,"avocade"])
string_data

0      ardvark
1    artichoke
2          NaN
3      avocade
dtype: str

In [18]:
print(string_data.isnull())
print(string_data.isna())
print(string_data.notnull())

0    False
1    False
2     True
3    False
dtype: bool
0    False
1    False
2     True
3    False
dtype: bool
0     True
1     True
2    False
3     True
dtype: bool

In [19]:
print(string_data.isnull().sum())

1

In [ ]:
#Dropna
data=pd.Series([1,NA,3.5,NA,7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [23]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [24]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [26]:
data.dropna(inplace=True)
data

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
#filling missing values
df=pd.DataFrame(np.random.randn(7,3))
df.iloc[:4,1]=NA
df.iloc[:2,2]=NA
df

          0         1         2
0 -0.088785       NaN       NaN
1  1.171405       NaN       NaN
2  0.159563       NaN  0.909346
3  0.042381       NaN -0.925008
4 -0.077381  0.033666  0.836454
5  0.525846 -0.001961  0.960230
6 -3.033795  0.904336  1.197420

In [38]:
df.fillna(0,inplace=True)

          0         1         2
0 -0.088785  0.000000  0.000000
1  1.171405  0.000000  0.000000
2  0.159563  0.000000  0.909346
3  0.042381  0.000000 -0.925008
4 -0.077381  0.033666  0.836454
5  0.525846 -0.001961  0.960230
6 -3.033795  0.904336  1.197420

In [39]:
df.fillna({1:1.1,2:2.2},inplace=True)

          0         1         2
0 -0.088785  0.000000  0.000000
1  1.171405  0.000000  0.000000
2  0.159563  0.000000  0.909346
3  0.042381  0.000000 -0.925008
4 -0.077381  0.033666  0.836454
5  0.525846 -0.001961  0.960230
6 -3.033795  0.904336  1.197420

In [59]:
#f fill
df=pd.DataFrame(np.random.randn(6,3))
df.iloc[2:,1]=NA
df.iloc[4:,2]=NA

In [60]:
df

          0         1         2
0 -1.167108  0.067258  0.592088
1  2.027501 -0.599526 -1.038223
2 -0.147343       NaN -0.968387
3 -0.322658       NaN -0.916211
4  0.046879       NaN       NaN
5 -0.855133       NaN       NaN

In [61]:
#df.fillna(method="ffill") -this is for older version

In [62]:
df.ffill(inplace=True,limit=2)

          0         1         2
0 -1.167108  0.067258  0.592088
1  2.027501 -0.599526 -1.038223
2 -0.147343 -0.599526 -0.968387
3 -0.322658 -0.599526 -0.916211
4  0.046879       NaN -0.916211
5 -0.855133       NaN -0.916211

In [63]:
df.ffill(inplace=True)

          0         1         2
0 -1.167108  0.067258  0.592088
1  2.027501 -0.599526 -1.038223
2 -0.147343 -0.599526 -0.968387
3 -0.322658 -0.599526 -0.916211
4  0.046879 -0.599526 -0.916211
5 -0.855133 -0.599526 -0.916211

In [64]:
df

          0         1         2
0 -1.167108  0.067258  0.592088
1  2.027501 -0.599526 -1.038223
2 -0.147343 -0.599526 -0.968387
3 -0.322658 -0.599526 -0.916211
4  0.046879 -0.599526 -0.916211
5 -0.855133 -0.599526 -0.916211

In [72]:
#remove duplicates
data=pd.DataFrame({"A":["one","Two"]*3+["Two"],
                   "B":[1,1,2,3,3,4,4]})
data.index=data.index+1
data

     A  B
1  one  1
2  Two  1
3  one  2
4  Two  3
5  one  3
6  Two  4
7  Two  4

In [73]:
data.duplicated()

1    False
2    False
3    False
4    False
5    False
6    False
7     True
dtype: bool

In [74]:
data.duplicated().sum()

np.int64(1)

In [75]:
data.drop_duplicates(inplace=True)

In [76]:
data

     A  B
1  one  1
2  Two  1
3  one  2
4  Two  3
5  one  3
6  Two  4